### ISSUE TITLE
clang-libc++ CI build error

### ISSUE THREAD

**Issue by sdarwin** [boostorg/build#704]
A few boost libraries already have a job configured where the compiler was set to "clang-libc++" and the installed package "clang-10". For example,  https://github.com/boostorg/detail . The "clang-libc++" job had been succeeding before, but now says "Building B2 engine.. Could not find a suitable toolset."   Might be related to the new compiler detection logic.   Was the job incorrectly defined?  

Other repositories get the same result.  boostorg/utility, boostorg/iterator, 

I have reduced the size of a travis file from 20 jobs to 3 jobs to complete faster, https://github.com/sdarwin/detail

Travis output:  https://travis-ci.org/github/sdarwin/detail/jobs/755425543

Job definition:

```
    - os: linux
      dist: xenial
      compiler: clang-libc++
      env: TOOLSET=clang COMPILER=clang++-10 CXXSTD=03,11,14,17,20 CXXFLAGS="-stdlib=libc++" LINKFLAGS="-stdlib=libc++"
      addons:
        apt:
          packages:
            - clang-10
            - libc++-10-dev
            - libc++abi-10-dev
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
```
